zookeeper:
  address: [c4cloudsrv.zk.hadoop.srv:11000]
  root: /pegasus/c4srv-metaproxy
  timeout: 1000 # ms
  table_watcher_cache_capacity: 1024

metric:
  type: falcon
  tags: [region=c3srv-cluster,service=meta_proxy]